notifiers = ["slack", "pync"]

[amazon]
url = "https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1"
wait_setup = 30
wait_success = 300
wait_fail = 5
wait_error = 30

[slack]
url = "https://hooks.slack.com/services/<my-unique-slack-hook-id>"